ARDUINO_VARIANT = nodemcuv2
# UPLOAD_PORT = /dev/nodemcu
UPLOAD_PORT = /dev/ttyUSB1
UPLOAD_SPEED=921600

SERIAL_PORT = $(UPLOAD_PORT)
SERIAL_BAUD = 115200

LOG_SERIAL_TO_FILE=yes
USER_DEFINE = -DTEST
OTA_IP = garage-door
OTA_PORT = 8266 
OTA_AUTH = 123
ESP8266_VERSION=.git
GLOBAL_USER_LIBDIR=../libraries
USER_LIBS=$(GLOBAL_USER_LIBDIR)/Adafruit_IO_Arduino \
          $(GLOBAL_USER_LIBDIR)/Adafruit_MQTT_Library \
					$(GLOBAL_USER_LIBDIR)/ESP8266DebounceButtons/src
include ../Esp8266-Arduino-Makefile/espXArduino.mk

