
// #ifndef ARDUINO_OTA_PASSWORD
#define ARDUINO_OTA_PASSWORD "leo"
// #endif



#define OPEN_CLOSE_BUTTON D7
#define ONE_WIRE_PIN D0
#define LED_GREEN D2
#define LED_RED D3
#define RELAY D8

// #define SWITCH_OPEN D5
// #define SWITCH_CLOSED D6
#define SONAR_TRIGGER D5
#define SONAR_ECHO D6
#define SONAR_MAX_DISTANCE 100
#define SONAR_READ_INTERVAL_COMMANDED 1000
#define SONAR_READ_INTERVAL_WAITING 10000
#define SONAR_READ_COMMANDED_FOR 60000

#define LED_ON HIGH
#define LED_OFF LOW

#define RELAY_CLOSED HIGH
#define RELAY_OPEN LOW
#define RELAY_TOGGLE_TIME 1000

#define TEMPERATURE_DELAY 600000

// Shouldnt need to change these.

